[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  targetPort = 3000
  port = 8888
  framework = "next"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment-specific settings
[build.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "development"

# Redirects for serverless functions
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 