[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "development"
  # Ensure devDependencies are installed during build
  NPM_FLAGS = "--production=false"

[dev]
  targetPort = 3000
  port = 8888
  framework = "next"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Base environment settings (development)
[build.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "development"

# Production environment settings (main branch)
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_ENV = "production"
  # Ensure devDependencies are installed during build
  NPM_FLAGS = "--production=false"

# Branch deployments (dev branch)
[context.dev.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "development"
  # Ensure devDependencies are installed during build
  NPM_FLAGS = "--production=false"

# Deploy preview settings (PRs)
[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "development"
  # Ensure devDependencies are installed during build
  NPM_FLAGS = "--production=false"

# Redirects for serverless functions
[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 